In [1]:
from keras.models import load_model

Using TensorFlow backend.


In [2]:
model=load_model('...')
#inter your model fime name to load
#below code is to test your model on other then dataset
#test.jpg and test2.jpeg are images of potato leaf

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [3]:
import cv2
import numpy as np

In [4]:
model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])

In [5]:
img = cv2.imread('test.JPG')

In [6]:
img = cv2.resize(img,(256,256))

In [7]:
img = np.reshape(img,[1,256,256,3])

In [ ]:
classes = model.predict_classes(img)

In [9]:
print(classes)

[2]


In [10]:
classes

array([2], dtype=int64)

In [12]:
model.predict(img)

array([[4.7658579e-03, 1.1969782e-06, 9.9523300e-01]], dtype=float32)

In [14]:
img1 = cv2.imread('test2.jpeg')

In [15]:
img1 = cv2.resize(img1,(256,256))

In [16]:
img1 = np.reshape(img1,[1,256,256,3])

In [17]:
classes = model.predict_classes(img1)

In [18]:
print(classes)

[0]


In [19]:
classes

array([0], dtype=int64)

In [21]:
predition=model.predict(img1)

In [22]:
print(predition)

[[1.0000000e+00 5.1709293e-20 1.4714168e-13]]
